; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = uno

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
build_flags =
  -Wall -Wextra -Wpedantic -Wunused -Wshadow -Wformat=2
  -Wno-unused-parameter
  -fno-exceptions
  -fno-threadsafe-statics
  -Os
  -mcall-prologues
  -fno-inline-functions-called-once
  -flto
  -ffunction-sections
  -fdata-sections
  -Wl,--gc-sections
  -D OBD_EXPERIMENTAL_SCREENS

[env:uno_debug]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
build_flags =
  ${env:uno.build_flags}
  -D OBD_DEBUG
  -D OBD_EXPERIMENTAL_SCREENS

[env:native]
platform = native
build_flags =
  -Wall
  -Wextra
  -DNATIVE_BUILD
  -Inative_arduino
test_build_src = yes
build_src_filter =
  +<obd/Model/*>
